name: draggan_project
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python >= 3.10
  - pip
  - numpy>=1.26.4
  - click>=8.3.1
  - pillow>=12.1.0
  - scipy>=1.15.3
  - pytorch>=2.1.2
  - torchvision>=0.16.2
  - cudatoolkit>=12.1
  - requests>=2.32.5
  - tqdm>=4.67.1
  - ninja=1.10.2
  - matplotlib>=3.10.8
  - imageio>=2.37.2
  - pip:
    - imgui==2.0.0
    - glfw==2.6.1
    - gradio==3.35.2
    - pyopengl==3.1.10
    - imageio-ffmpeg==0.6.0
    - pyspng-seunglab==1.1.2
    - huggingface_hub>=1.3.2
    - hf_transfer>=0.1.9
